server.port: 8081

spring:
  application.name: config
  cloud.config.server.git.uri: https://github.com/kuzma87/application-config.git

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl.defaultZone: http://localhost:8082/eureka/
